### ISSUE TITLE
Feature request: Adapt the LGoodDatePicker components for use inside the NetBeans visual designer.

### ISSUE THREAD

**Issue by blegoh** [LGoodDatePicker/LGoodDatePicker#12] opened 2016-04-17 00:35 UTC
i got this error when using drag and drop from netbeans. i get this error when i click the date
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.github.lgooddatepicker.zinternaltools.CalendarPanel.drawCalendar(CalendarPanel.java:321)
	at com.github.lgooddatepicker.zinternaltools.CalendarPanel.buttonPreviousMonthActionPerformed(CalendarPanel.java:261)
	at com.github.lgooddatepicker.zinternaltools.CalendarPanel.lambda$initComponents$1(CalendarPanel.java:783)

**Comment by BlakeTNC** [comment] 2016-04-17 01:58
Hello blegoh,
    The LGoodDatePicker components have not been designed (adapted) to be used with the NetBeans visual designer. The components should be added to GUI forms programmatically. If you wish to use the visual designer for all other parts of your forms, I would suggest a procedure similar to the following:

   Design all other parts of your form in the visual designer, and place a JPanel (as a "placeholder") in the position that you would like your date picker to occupy. This will help you get a feel for what your forms will look like. You would probably want to color the placeholder panel white instead of the default color. Then, in the component initialization of your form class (or the constructor), you can add the following code:

DatePicker datePicker = new DatePicker();
yourDatePickerPanel.add(datePicker); 

When your program is run, you will see the date picker occupy the position where you placed your panel.

Alternatively, it would also be possible for a programmer with the proper skill and motivation to adapt the LGoodDatePicker components to work within the NetBeans visual designer. This is a feature that I would be pleased to see added to the library. I don't yet know the details of how to do it myself, but if you know how to accomplish that, please add any necessary instructions to this issue thread. If it's simple enough to accomplish, I might program it myself, or another programmer may pick up the task.

warm regards,
Blake

**Comment by karlmortensen** [comment] 2016-04-18 13:33
It worked for me. I added it to the NetBeans Palette with "Create New Category", dragged and dropped, added the dependencies it needed, built, then removed it from my Palette, and it seems to function. At least for `com.github.lgooddatepicker.datetimepicker.DateTimePicker` that is. It did have a little difficulty with where it actually showed up in the JPanel, but I think that's because of the layout I was using.

**Comment by BlakeTNC** [comment] 2016-04-18 20:09
karlmortensen, 
Thank you for testing that. I assumed a swing component might have to meet some extra specifications to work with the Netbeans visual designer, but maybe that's not the case.

From blegoh's pasted text, their error appears to be due to a null settings variable (DatePickerSettings) in the CalendarPanel class. I don't know for sure what caused that situation, but perhaps they tried to instantiate the CalendarPanel outside of the context of a date picker? CalendarPanel is not currently designed to be used independently.

I would be curious to know if your drag-drop test also works with a single DatePicker instance. 

Warm regards, 
Blake

**Comment by BlakeTNC** [comment] 2016-04-18 20:17
PS, At some point, I need to set the minimum size of the components based on the current settings. (Based on the font metrics of the current font, used together with the longest standard time string of the current display format). I have not got around to that yet, but that enhancement was on my to do list. The default behavior has been working pretty well in the meantime. If the positioning behavior you experienced was something along the lines of the fields were way too small in the horizontal direction, then that missing feature could be the cause.

**Comment by BlakeTNC** [comment] 2016-04-25 17:49
Hello blegoh,
   The release of [LGoodDatePicker 5.2.2](https://github.com/LGoodDatePicker/LGoodDatePicker/releases) includes a bug fix for a null pointer exception that was occurring for some users. Please let me know if the library works for you with the NetBeans visual designer, using the new release. This issue will be closed within a few days if no additional concerns are reported. Thank you.
Warm regards,
Blake

**Comment by BlakeTNC** [comment] 2016-04-28 19:15
Closing this issue as non-reproducible. The issue can be re-opened with additional reports or information on how to reproduce the error. 
-Blake

**Closed by BlakeTNC** 2016-04-28 19:15 UTC
Labels: enhancement
