### ISSUE TITLE
getDisplayedYearMonth

### ISSUE THREAD

**Issue by laskovenko** [LGoodDatePicker/LGoodDatePicker#53] opened 2017-06-02 12:35 UTC
Hi,

We are trying to extend the component and need getDisplayedYearMonth() as public method. 
Can you provide one in the next release?
The setDisplayedYearMonth is already available.

Thank you in advance.
Konstantin.

**Comment by BlakeTNC** [comment] 2017-06-02 16:43
Hi Konstantin,
No problem. I added the requested function and committed it to github. However, a release including this function may still be a ways off because I would probably either wait for some more significant changes or for some time to pass before creating a new release.

In the meantime, you could build a jar from the repository if desired. You would need to comment out the maven-gpg-plugin in the pom file, open the project in NetBeans (a tested IDE), and hit clean and build. 

I know that the requested function is only an accessor, but please let me know if there is any unexpected behavior. I briefly glanced through the places where that variable is used, and it looks like the the variable value should probably change during moments and events where the changes should be expected. (In other words, from a brief code review, the timing of the changes is expected to be intuitive.)

Warm regards,
Blake

**Closed by BlakeTNC** 2017-06-02 16:43 UTC

**Comment by BlakeTNC** [comment] 2017-06-02 16:55
PS, Actually I'm not certain what's required to build directly from the repository. (I've never had to do that, and I don't think anyone has asked about it.) The main POM file is full of stuff that's needed for creating releases. If commenting out the maven-gpg-plugin does not build the project successfully, you could also try replacing the repository POM file with the "generic" POM file that is included in the files distributed with the [latest release](https://github.com/LGoodDatePicker/LGoodDatePicker/releases).

**Comment by BlakeTNC** [comment] 2017-06-02 17:05
PPS, I just realized I could build it for you much more easily. Here is are all the files that would be included in a github release. 
Thanks,
-Blake

[LGDP 10.2.3 with getDisplayedYearMonth, BETA SOFTWARE.zip](https://github.com/LGoodDatePicker/LGoodDatePicker/files/1048390/LGDP.10.2.3.with.getDisplayedYearMonth.BETA.SOFTWARE.zip)

**Comment by laskovenko** [comment] 2017-06-06 08:50
Hi, 

thank you very much for such surprisingly quick feedback. And for the release binaries made for us. 

Best regards,
Konstantin

**Comment by BlakeTNC** [comment] 2017-07-05 23:27
LGoodDatePicker 10.3.1 has been released with these features. This release is available in the [Release Section]( https://github.com/LGoodDatePicker/LGoodDatePicker/releases), on [Maven Central](http://search.maven.org/#search%7Cga%7C1%7CLGoodDatePicker), and as an [LGoodDatePicker Backport](https://github.com/LGoodDatePicker/LGoodDatePicker/releases/tag/Backports).
-Blake
