### ISSUE TITLE
Feature Request: get notifed if current view of CalendarPanel is changed 

### ISSUE THREAD

**Issue by laskovenko** [LGoodDatePicker/LGoodDatePicker#54] opened 2017-06-07 15:18 UTC
Hi,

I am trying to use **CalendarPanel** to provide an outlook-like control holding multiple calendar panels but behaving like a single calendar control (see the screenshot below). For this purpose we need to get notified if the current view, namely month/year, is changed (June on the screenshot) and than adjust year/month for the other panels (set July to the second calendar on the screenshot). 
The notification can be send as event at the end of **drawCalendar** method if the **displayedYearMonth**  was really changed to a new value at the beginning of this method. Any other implementation is also acceptable. The main goal is to get notified as soon as **displayedYearMonth**  is changed.

Thanks and best regards,
Konstantin
![2017-06-07 16_50_23-](https://user-images.githubusercontent.com/2714565/26886284-3eaa746e-4ba5-11e7-93df-4b27520b8a54.png)

**Comment by BlakeTNC** [comment] 2017-06-30 09:41
@laskovenko,
    This feature has been implemented, and committed to the master branch. See commit 38e46e84d43800224763a73cf5a499aa0f054c79.

I intend to create a new release which includes all the recent improvements within a couple weeks, after early adopters have a chance to test the new functionality. Let me know if this new feature works for you as intended. Also holler if you need a release but I have not created one within 2 weeks. 

Thanks for the feature request!
-Blake

**Closed by BlakeTNC** 2017-06-30 09:41 UTC
Labels: enhancement

**Comment by BlakeTNC** [comment] 2017-06-30 09:56
PS, All the special-purpose Maven Central release related plugins (and gpg signing plugins) were commented out of the pom file to make it easier for others besides myself to build the project. I believe that anyone should be able to build it more easily now (just by clicking build), but I also attached beta binaries here.  

Also, the new notification functionality is included in the FullDemo. Run the demo and click on the independent calendar panel, to see the new YearMonth notifications appear in the text area. 

[LGoodDatePicker-10.2.7-BETA.zip](https://github.com/LGoodDatePicker/LGoodDatePicker/files/1114750/LGoodDatePicker-10.2.7-BETA.zip)

**Comment by BlakeTNC** [comment] 2017-07-05 23:25
LGoodDatePicker 10.3.1 has been released with these features. This release is available in the [Release Section]( https://github.com/LGoodDatePicker/LGoodDatePicker/releases), on [Maven Central](http://search.maven.org/#search%7Cga%7C1%7CLGoodDatePicker), and as an [LGoodDatePicker Backport](https://github.com/LGoodDatePicker/LGoodDatePicker/releases/tag/Backports).
-Blake
